# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61b9bcbf0ebf258fd4be66422ce5bd839d2cbb69249e081024fcbae752dffa4b1882a3550ab4e825211a90d71ef545c5a3b25edc63d6e2e7f80f88dadf3f8a20
  sendgrid_api_key: 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
  twitter_api_key: 1tEJgkQdJ1g7DI8xIlzfIOsBv
  twitter_api_secret: 4yZAtbUdMXeEWCSFqmr1oTdaY3psqOVoNxMiH1MR5sxaWVthw4

test:
  secret_key_base: 4292de50177708364d456d00b260b1e1b54462f13859c410af7cedfc1800e2237e85499c57e6503569f46184be49093b2f44c5343b4b257ff19505ea1b178085

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: 1tEJgkQdJ1g7DI8xIlzfIOsBv
  twitter_api_secret: 4yZAtbUdMXeEWCSFqmr1oTdaY3psqOVoNxMiH1MR5sxaWVthw4
